In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import sys
from pathlib import Path

ROOT_DIR = Path.cwd().parent
sys.path.append(str(ROOT_DIR))

In [9]:
from config.config import Data_Path

In [10]:


df = pd.read_csv(Data_Path)

df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [11]:
df.shape

(10000, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [12]:
df.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [13]:
df.describe()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
count,9971.000000,9981.000000,9970.000000,9978.000000,9975.000000,9974.000000,9978.000000,9974.000000,9980.000000
mean,49.296259,149.757740,225.425577,29.077269,6.991329,250.734409,120.142213,7.472201,12.456271
std,18.193970,17.572969,43.575809,6.307098,1.753195,87.067226,23.584011,4.340248,4.323426
min,18.000000,120.000000,150.000000,18.002837,4.000605,100.000000,80.000000,0.003647,5.000236
25%,34.000000,134.000000,187.000000,23.658075,5.449866,176.000000,99.000000,3.674126,8.723334
50%,49.000000,150.000000,226.000000,29.079492,7.003252,250.000000,120.000000,7.472164,12.409395
75%,65.000000,165.000000,263.000000,34.520015,8.531577,326.000000,141.000000,11.255592,16.140564
max,80.000000,180.000000,300.000000,39.996954,9.999952,400.000000,160.000000,14.997087,19.999037

In [14]:
df.dtypes

Age                     float64
Gender                   object
Blood Pressure          float64
Cholesterol Level       float64
Exercise Habits          object
Smoking                  object
Family Heart Disease     object
Diabetes                 object
BMI                     float64
High Blood Pressure      object
Low HDL Cholesterol      object
High LDL Cholesterol     object
Alcohol Consumption      object
Stress Level             object
Sleep Hours             float64
Sugar Consumption        object
Triglyceride Level      float64
Fasting Blood Sugar     float64
CRP Level               float64
Homocysteine Level      float64
Heart Disease Status     object
dtype: object

In [15]:
numeric_columns = df.select_dtypes(include=np.number).columns

numeric_columns

Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')

In [16]:
summary = df[numeric_columns].describe().T

summary

,count,mean,std,min,25%,50%,75%,max
Age,9971.0,49.296259,18.193970,18.000000,34.000000,49.000000,65.000000,80.000000
Blood Pressure,9981.0,149.757740,17.572969,120.000000,134.000000,150.000000,165.000000,180.000000
Cholesterol Level,9970.0,225.425577,43.575809,150.000000,187.000000,226.000000,263.000000,300.000000
BMI,9978.0,29.077269,6.307098,18.002837,23.658075,29.079492,34.520015,39.996954
Sleep Hours,9975.0,6.991329,1.753195,4.000605,5.449866,7.003252,8.531577,9.999952
Triglyceride Level,9974.0,250.734409,87.067226,100.000000,176.000000,250.000000,326.000000,400.000000
Fasting Blood Sugar,9978.0,120.142213,23.584011,80.000000,99.000000,120.000000,141.000000,160.000000
CRP Level,9974.0,7.472201,4.340248,0.003647,3.674126,7.472164,11.255592,14.997087
Homocysteine Level,9980.0,12.456271,4.323426,5.000236,8.723334,12.409395,16.140564,19.999037

In [17]:
df[numeric_columns].skew()

Age                   -0.006789
Blood Pressure         0.013907
Cholesterol Level     -0.007120
BMI                   -0.021342
Sleep Hours            0.000172
Triglyceride Level     0.006142
Fasting Blood Sugar   -0.008915
CRP Level             -0.004069
Homocysteine Level     0.007886
dtype: float64

In [32]:
Q1=df["Blood Pressure"].quantile(0.25)
Q3=df["Blood Pressure"].quantile(0.75)
print("Blood Pressure")
IQR=Q3-Q1
lower_fence=Q1-IQR*1.5
upper_fence=Q3+IQR*1.5
print("Q1: ",Q1)
print("Q2: ",Q3)
print("IQR: ",IQR)
print("lower frnce: ",lower_fence,)
print("upper fence: ", upper_fence,"\n")

Q1=df["BMI"].quantile(0.25)
Q3=df["BMI"].quantile(0.75)
print("BMI")
IQR=Q3-Q1
lower_fence=Q1-IQR*1.5
upper_fence=Q3+IQR*1.5
print("Q1: ",Q1)
print("Q2: ",Q3)
print("IQR: ",IQR)
print("lower frnce: ",lower_fence,)
print("upper fence: ", upper_fence,"\n")

Q1=df["Triglyceride Level"].quantile(0.25)
Q3=df["Triglyceride Level"].quantile(0.75)
print("Triglyceride Level")
IQR=Q3-Q1
lower_fence=Q1-IQR*1.5
upper_fence=Q3+IQR*1.5
print("Q1: ",Q1)
print("Q2: ",Q3)
print("IQR: ",IQR)
print("lower frnce: ",lower_fence,)
print("upper fence: ", upper_fence,"\n")


Q1=df["Homocysteine Level"].quantile(0.25)
Q3=df["Homocysteine Level"].quantile(0.75)
print("Homocysteine Level")
IQR=Q3-Q1
lower_fence=Q1-IQR*1.5
upper_fence=Q3+IQR*1.5
print("Q1: ",Q1)
print("Q2: ",Q3)
print("IQR: ",IQR)
print("lower frnce: ",lower_fence,)
print("upper fence: ", upper_fence,"\n")

Q1=df["Fasting Blood Sugar"].quantile(0.25)
Q3=df["Fasting Blood Sugar"].quantile(0.75)
print("Fasting Blood Sugar")
IQR=Q3-Q1
lower_fence=Q1-IQR*1.5
upper_fence=Q3+IQR*1.5
print("Q1: ",Q1)
print("Q2: ",Q3)
print("IQR: ",IQR)
print("lower frnce: ",lower_fence,)
print("upper fence: ", upper_fence,"\n")

Q1=df["Age"].quantile(0.25)
Q3=df["Age"].quantile(0.75)
print("Age")

IQR=Q3-Q1
lower_fence=Q1-IQR*1.5
upper_fence=Q3+IQR*1.5
print("Q1: ",Q1)
print("Q2: ",Q3)
print("IQR: ",IQR)
print("lower frnce: ",lower_fence,)
print("upper fence: ", upper_fence,"\n")

Blood Pressure
Q1:  134.0
Q2:  165.0
IQR:  31.0
lower frnce:  87.5
upper fence:  211.5

BMI
Q1:  23.658075171017085
Q2:  34.5200150669223
IQR:  10.861939895905213
lower frnce:  7.365165327159264
upper fence:  50.81292491078012

Triglyceride Level
Q1:  176.0
Q2:  326.0
IQR:  150.0
lower frnce:  -49.0
upper fence:  551.0

Homocysteine Level
Q1:  8.723334227972153
Q2:  16.140563913962453
IQR:  7.4172296859903
lower frnce:  -2.4025103010132973
upper fence:  27.266408442947903

Fasting Blood Sugar
Q1:  99.0
Q2:  141.0
IQR:  42.0
lower frnce:  36.0
upper fence:  204.0

Age
Q1:  34.0
Q2:  65.0
IQR:  31.0
lower frnce:  -12.5
upper fence:  111.5